# Section 3

## Today's Topics
<ul>
<li>Review TF Basics</li>
<li>More on TF</li>
<li>Loss Functions</li>
</ul>

### Extra Resources
<ul>
<li><a href='https://www.tensorflow.org/'>TensorFlow</a></li>
<li><a href='https://www.tensorflow.org/get_started/'>TF Getting Started Tutorials</a></li>
<li><a href='https://www.tensorflow.org/programmers_guide/'>TF Programmer's Guide</a></li>
<li><a href='http://cs231n.github.io/linear-classify/'>Notes on Linear Classification</a> - see this if you are confused on what we have been doing.
<li><a href='http://ufldl.stanford.edu/tutorial/supervised/SoftmaxRegression/'>Notes on Softmax Regression</a> - see this if you are confused on what we are doing now.
</ul>

### Open Questions
What is still confusing? Let's work through some examples together.

Potential topics:
<ul>
<li>Activation and weight sizes</li>
<li>Hidden layers</li>
<li>Activation functions</li>
<li>Initializing variables</li>
<li>Getting outputs from your graph
</ul>

In [2]:
import tensorflow as tf
import numpy as np

sess = tf.Session()

### In class examples
inputs = tf.placeholder(tf.float32, (None, 2))
labels = tf.placeholder(tf.float32, (None, 1))
outputs = tf.layers.dense(inputs, 1)

loss = tf.reduce_mean(tf.nn.sigmoid_cross_entropy_with_logits(labels=labels, logits=outputs))
print(loss)

###

Tensor("Mean:0", shape=(), dtype=float32)


### More on TensorFlow

In [3]:
# Reshaping data
inputs = tf.placeholder(tf.float32, (None, 32, 32, 3))
print (inputs)

# Flattening
flat = tf.contrib.layers.flatten(inputs)
print (flat)


# Other reshapes
shaped = tf.reshape(inputs, shape=[-1, 32*32, 3])
print (shaped)
shaped = tf.reshape(inputs, shape=[10, 32*32, 3])
print (shaped)

Tensor("Placeholder_2:0", shape=(?, 32, 32, 3), dtype=float32)
Tensor("Flatten/Reshape:0", shape=(?, 3072), dtype=float32)
Tensor("Reshape:0", shape=(?, 1024, 3), dtype=float32)
Tensor("Reshape_1:0", shape=(10, 1024, 3), dtype=float32)


In [4]:
# One hot vectors

# We have labels [2, 1, 0, 3]
# We want labels [[0, 0, 1, 0], [0, 1, 0, 0], [1, 0, 0, 0], [0, 0, 0, 1]]
labels = tf.placeholder(tf.int32, (10))  # hardcoding in sample values, size

onehot = tf.one_hot(labels, 5)
print (onehot)

print (sess.run(onehot, {labels: [0,1,2,3,4,0,1,2,3,4]}))


Tensor("one_hot:0", shape=(10, 5), dtype=float32)
[[ 1.  0.  0.  0.  0.]
 [ 0.  1.  0.  0.  0.]
 [ 0.  0.  1.  0.  0.]
 [ 0.  0.  0.  1.  0.]
 [ 0.  0.  0.  0.  1.]
 [ 1.  0.  0.  0.  0.]
 [ 0.  1.  0.  0.  0.]
 [ 0.  0.  1.  0.  0.]
 [ 0.  0.  0.  1.  0.]
 [ 0.  0.  0.  0.  1.]]


In [5]:
# Layers
inputs2 = tf.placeholder(tf.float32, (None, 10))

# Fully-connected layers
h = tf.layers.dense(inputs2, 100, activation=tf.nn.relu, name='hidden_layer')
print(h)

o = tf.layers.dense(h, 1)
print(o)

#h = tf.layers.dense(inputs2, 20, activation=tf.nn.relu, kernel_initializer=, name='hidden_layer')
# Other layers?

Tensor("hidden_layer/Relu:0", shape=(?, 100), dtype=float32)
Tensor("dense_2/BiasAdd:0", shape=(?, 1), dtype=float32)


In [8]:
inputs3 = tf.placeholder(tf.float32, (None, 10))
h1 = tf.layers.dense(inputs3, 100, activation=tf.nn.relu)
h2 = tf.layers.dense(h1, 100, activation=tf.nn.relu)
h3 = tf.layers.dense(h2, 100, activation=tf.nn.relu)
h4 = tf.layers.dense(h3, 100, activation=tf.nn.relu)
h5 = tf.layers.dense(h4, 100, activation=tf.nn.relu)
o = tf.layers.dense(h5, 1)
print (inputs3)
print (h1)
print (h2)
print (h3)
print (h4)
print (h5)
print (o)

Tensor("Placeholder_7:0", shape=(?, 10), dtype=float32)
Tensor("dense_14/Relu:0", shape=(?, 100), dtype=float32)
Tensor("dense_15/Relu:0", shape=(?, 100), dtype=float32)
Tensor("dense_16/Relu:0", shape=(?, 100), dtype=float32)
Tensor("dense_17/Relu:0", shape=(?, 100), dtype=float32)
Tensor("dense_18/Relu:0", shape=(?, 100), dtype=float32)
Tensor("dense_19/BiasAdd:0", shape=(?, 1), dtype=float32)


### Loss Functions

<a href='https://www.tensorflow.org/versions/r1.3/api_docs/python/tf/nn/softmax_cross_entropy_with_logits'>Softmax Cross Entropy With Logits</a><br/>
<a href='https://www.tensorflow.org/versions/r1.3/api_docs/python/tf/nn/sparse_softmax_cross_entropy_with_logits'>Sparse Softmax Cross Entropy</a><br>
<a href='https://www.tensorflow.org/versions/r1.3/api_docs/python/tf/nn/sigmoid_cross_entropy_with_logits'>Sigmoid Cross Entropy With Logits</a><br/>
<a href='http://peterroelants.github.io/posts/neural_network_implementation_intermezzo02/'>Notes on Softmax</a>

Look at the documentation:
<ul>
<li>Does a loss function ask for unscaled logits? Why?</li>
<li>What order should you pass your arguments? What happens if you flip one?</li>
<li>Where can you find the TensorFlow source code?</li>
</ul>

In [11]:
# 2 branches 
#   -- optimizer -> sotmax C.E. -> dense -> dense -> hidden
#   -- argmax -> softmax ------------^

inputs4 = tf.placeholder(tf.float32, (5), name='sm_in')
probs = tf.nn.softmax(inputs4)
pred = tf.argmax(probs)
#input_data = [1,1,1,1,1]
input_data = [1,2,3,4,5]
print(sess.run(probs, {inputs4:input_data}))
print(sess.run(pred, {inputs4:input_data}))

[ 0.01165623  0.03168492  0.08612854  0.23412165  0.63640863]
4


### Optimization
<a href='https://distill.pub/2017/momentum/'>Why Momentum Really Works - Distill</a>